declare const classNames: {
  readonly topContainer: 'topContainer';
  readonly mainMenu: 'mainMenu';
  readonly columnsThree: 'columnsThree';
  readonly columnsTwo: 'columnsTwo';
  readonly thirdColumn: 'thirdColumn';
  readonly firstColumn: 'firstColumn';
  readonly contentContainer: 'contentContainer';
  readonly separator: 'separator';
  readonly separatorLeft: 'separatorLeft';
  readonly separatorRight: 'separatorRight';
  readonly containerForMainMenu: 'containerForMainMenu';
  readonly columns: 'columns';
  readonly column: 'column';
  readonly mainMenuSearch: 'mainMenuSearch';
  readonly mainMenuSearchLabel: 'mainMenuSearchLabel';
  readonly mainMenuSearchSpacing: 'mainMenuSearchSpacing';
  readonly srOnly: 'srOnly';
};
export default classNames;
