declare const classNames: {
  readonly successIcon: 'successIcon';
  readonly successIconLinkMargin: 'successIconLinkMargin';
  readonly cancelIcon: 'cancelIcon';
  readonly fileSpinner: 'fileSpinner';
  readonly spinner: 'spinner';
  readonly fileNameContainer: 'fileNameContainer';
  readonly fileContentContainer: 'fileContentContainer';
  readonly iconWrapper: 'iconWrapper';
  readonly cardWithAnimatedBorder: 'cardWithAnimatedBorder';
  readonly fileList: 'fileList';
  readonly fileListItem: 'fileListItem';
  readonly fileListGrid: 'fileListGrid';
  readonly fileListText: 'fileListText';
  readonly fileListIcon: 'fileListIcon';
  readonly fileListContainer: 'fileListContainer';
  readonly fileListLink: 'fileListLink';
  readonly fileListFile: 'fileListFile';
  readonly fileListFileError: 'fileListFileError';
  readonly hasLink: 'hasLink';
};
export default classNames;
