/* automatisk genererte types */
export const icon: string;
export const icon_large: string;
export const icon_extraLarge: string;
export const header: string;
export const title: string;
export const title_large: string;
export const title_extraLarge: string;
export const content: string;
export const content_extraLarge: string;
export const contentIndented: string;
export const navigationTile: string;
export const navigationTile_extraLarge: string;
export const navigationTile_medium: string;
export const navigationTile_large: string;
export const titleWrapper: string;
export const iconWrapper: string;
export const iconWrapper_medium: string;
export const iconWrapper_large: string;
