declare const classNames: {
  readonly icon: 'icon';
  readonly icon_large: 'icon_large';
  readonly icon_extraLarge: 'icon_extraLarge';
  readonly header: 'header';
  readonly title: 'title';
  readonly title_large: 'title_large';
  readonly title_extraLarge: 'title_extraLarge';
  readonly description: 'description';
  readonly description_extraLarge: 'description_extraLarge';
  readonly descriptionIndented: 'descriptionIndented';
  readonly navigationTile: 'navigationTile';
  readonly navigationTile_extraLarge: 'navigationTile_extraLarge';
  readonly navigationTile_medium: 'navigationTile_medium';
  readonly navigationTile_large: 'navigationTile_large';
  readonly titleWrapper: 'titleWrapper';
  readonly iconWrapper: 'iconWrapper';
  readonly iconWrapper_medium: 'iconWrapper_medium';
  readonly iconWrapper_large: 'iconWrapper_large';
};
export = classNames;
