declare const classNames: {
  readonly wrapperInternalLayout: 'wrapperInternalLayout';
  readonly aside: 'aside';
  readonly main: 'main';
  readonly topHeading: 'topHeading';
  readonly block: 'block';
  readonly breadcrumbs: 'breadcrumbs';
  readonly noMargin: 'noMargin';
  readonly listRow: 'listRow';
  readonly tagRow: 'tagRow';
  readonly marginBottomL: 'marginBottomL';
  readonly card: 'card';
  readonly cardContent: 'cardContent';
  readonly wideContent: 'wideContent';
  readonly mainExternal: 'mainExternal';
  readonly miniNav: 'miniNav';
  readonly article: 'article';
  readonly marginTopM: 'marginTopM';
  readonly marginRightM: 'marginRightM';
  readonly checkIconContainer: 'checkIconContainer';
  readonly checkIcon: 'checkIcon';
  readonly panel: 'panel';
  readonly stepList: 'stepList';
  readonly stepListStep: 'stepListStep';
  readonly preLine: 'preLine';
};
export default classNames;
