declare const classNames: {
  readonly wrapperInternalLayout: 'wrapperInternalLayout';
  readonly aside: 'aside';
  readonly main: 'main';
  readonly topHeading: 'topHeading';
  readonly block: 'block';
  readonly breadcrumbs: 'breadcrumbs';
  readonly noMargin: 'noMargin';
  readonly listRow: 'listRow';
  readonly tagRow: 'tagRow';
  readonly marginBottomL: 'marginBottomL';
  readonly card: 'card';
  readonly cardContent: 'cardContent';
  readonly wideContent: 'wideContent';
  readonly mainExternal: 'mainExternal';
  readonly miniNav: 'miniNav';
  readonly article: 'article';
  readonly marginTopM: 'marginTopM';
  readonly marginTopL: 'marginTopL';
  readonly marginRightM: 'marginRightM';
  readonly flex: 'flex';
  readonly adress: 'adress';
  readonly postalCode: 'postalCode';
  readonly city: 'city';
  readonly phone: 'phone';
  readonly preLine: 'preLine';
};
export default classNames;
